apiVersion: v1
kind: Service
metadata:
  name: vault-secretstore-lab-svc
  namespace: dapr-vault-lab
spec:
  selector:
    dapr: vault-lab
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000