apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault-lab
  namespace: ob-apps
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:  
    - name: vaultAddr
      value: http://vault-internal.default:8200
    - name: vaultToken
      value: "hvs.usorTfSPa9nyxUBDPuRxtv1n"
    - name: vaultKVPrefix
      value: "dapr/go-secret-lab"
    - name: vaultKVUsePrefix
      value: "true"
    - name: enginePath
      value: "secret"
scopes:
  - vault-secretstore-lab